spring.application.name=user-service
server.port=8019

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ExamUser
spring.datasource.username=postgres
spring.datasource.password=passer
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Redis
spring.cache.type=redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Swagger
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000